import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import { Toaster } from "@/app/components/ui/toaster";
import { AuthProvider } from "@/context/auth"; // Certifique-se de ajustar o caminho
import UserNav from "./components/common/nav/userNav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-slate-100`}>
        {/* Envolvendo toda a aplicação com AuthProvider */}
        <AuthProvider>
          <UserNav /> {/* Usa o componente de navegação */}
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
